"use client";
import React, { useState } from "react";
import {
  HelpCircle,
  Zap,
  Shield,
  Clock,
  CircleMinus,
  CirclePlus,
} from "lucide-react";

// --- TYPE DEFINITIONS FOR DATA STRUCTURE ---
interface SubPoint {
  title: string;
  description: string;
}

interface Question {
  q: string;
  a: string;
  subPoints?: SubPoint[];
}

interface FaqCategory {
  category: string;
  icon: React.ComponentType<{ className?: string }>;
  questions: Question[];
}

// Reusing the original data structure, explicitly typed
const faqs: FaqCategory[] = [
  {
    category: "Getting Started",
    icon: Zap,
    questions: [
      {
        q: "How quickly can I get my laptop delivered?",
        a: "We offer same-day delivery within city limits for orders placed before 2 PM. Outside city limits, expect delivery within 24-48 hours. All laptops come with real-time tracking.",
        subPoints: [
          {
            title: "Same-Day Delivery",
            description:
              "Available for orders within 50km radius placed before 2 PM",
          },
          {
            title: "Standard Delivery",
            description:
              "48-hour delivery for all other locations across India",
          },
        ],
      },
      {
        q: "What makes your refurbished laptops different?",
        a: "Every laptop undergoes a 50-point quality check, complete hardware diagnostics, and professional cleaning. We replace batteries below 80% health and provide a detailed condition report with every purchase.",
        subPoints: [
          {
            title: "Hardware Inspection",
            description: "CPU, RAM, motherboard tested under stress conditions",
          },
          {
            title: "Battery Certification",
            description: "Minimum 80% health or free replacement included",
          },
        ],
      },
    ],
  },
  {
    category: "Warranty & Support",
    icon: Shield,
    questions: [
      {
        q: "What's included in your warranty?",
        a: "All laptops come with a 6-month comprehensive warranty covering hardware failures, battery issues, and screen defects. Extended 1-year and 2-year warranty options available at checkout.",
      },
      {
        q: "Can I return my laptop if I'm not satisfied?",
        a: "Absolutely. 30-day no-questions-asked return policy. If you're not happy, we'll refund 100% of your money. Just keep the original packaging.",
        subPoints: [
          {
            title: "30-Day Window",
            description: "Full refund if returned within 30 days of delivery",
          },
          {
            title: "Original Packaging Required",
            description: "Keep the box and accessories for hassle-free returns",
          },
        ],
      },
    ],
  },
  {
    category: "Technical Specs",
    icon: Clock,
    questions: [
      {
        q: "How do I know the laptop specs are accurate?",
        a: "We provide full system diagnostic reports generated by professional tools. You'll receive screenshots of CPU-Z, HWiNFO, and battery health reports before delivery.",
      },
      {
        q: "Are the laptops upgradeable?",
        a: "Most models support RAM and SSD upgrades. We offer free consultation on upgrade compatibility and can perform upgrades at cost price.",
      },
    ],
  },
];

// --- HELPER COMPONENT (Typed with React.FC) ---

interface FaqItemProps {
  item: Question;
  isOpen: boolean;
  toggle: () => void;
}

const FaqItem: React.FC<FaqItemProps> = ({ item, isOpen, toggle }) => {
  return (
    <div className='border-b'>
      <button
        onClick={toggle}
        className='flex justify-between items-center w-full py-3.5 sm:py-4 text-base sm:text-lg font-medium hover:text-blue-600 transition-colors duration-200 text-left'
      >
        <span className='text-gray-900'>{item.q}</span>
        {isOpen ? (
          <CircleMinus className='w-5 h-5 text-blue-600 transition-all duration-300' />
        ) : (
          <CirclePlus className='w-5 h-5 text-gray-500 transition-all duration-300' />
        )}
      </button>
      <div
        className={`overflow-hidden transition-all duration-300 ease-in-out ${
          isOpen ? "max-h-screen opacity-100 pb-3 sm:pb-4" : "max-h-0 opacity-0"
        }`}
      >
        <div className='text-gray-700 text-sm sm:text-base space-y-3 pl-2'>
          <p className='mb-2'>{item.a}</p>
          {item.subPoints && item.subPoints.length > 0 && (
            <ul className='list-disc pl-5 space-y-1 text-xs sm:text-sm text-gray-600'>
              {item.subPoints.map((point, idx) => (
                <li key={idx}>
                  <span className='font-semibold text-gray-800'>
                    {point.title}:
                  </span>{" "}
                  {point.description}
                </li>
              ))}
            </ul>
          )}
        </div>
      </div>
    </div>
  );
};

// --- MAIN COMPONENT (Typed) ---

export default function SimpleFAQComponent() {
  const [openItems, setOpenItems] = useState<Record<string, boolean>>({});
  const [selectedCategory, setSelectedCategory] = useState<string>("all");

  const toggleItem = (category: string, index: number) => {
    const key = `${category}-${index}`;
    setOpenItems((prev) => ({
      ...prev,
      [key]: !prev[key],
    }));
  };

  const filteredFaqs = faqs
    .map((category) => ({
      ...category,
      questions: category.questions.filter(
        () =>
          selectedCategory === "all" || category.category === selectedCategory
      ),
    }))
    .filter((category) => category.questions.length > 0);

  const allCategories = [
    { category: "all", icon: HelpCircle, questions: [] },
    ...faqs,
  ];

  return (
    <div className='w-full bg-gray-200 py-8 sm:py-12 px-4 sm:px-6 lg:px-8'>
      <div className='max-w-4xl mx-auto'>
        {/* Header (Responsive Title Size) */}
        <div className='text-center mb-8 sm:mb-10'>
          <h1 className='text-2xl sm:text-3xl font-extrabold text-gray-900 mb-2'>
            Frequently Asked Questions
          </h1>
          <p className='text-sm sm:text-base text-gray-600'>
            Find quick answers to the most common questions about our products.
          </p>
        </div>

        {/* Filter Tabs */}
        <div className='space-y-4 sm:space-y-6 mb-6 sm:mb-8'>
          <div className='flex items-center justify-center flex-wrap gap-2'>
            {allCategories.map((cat) => (
              <button
                key={cat.category}
                onClick={() => setSelectedCategory(cat.category)}
                className={`px-3 py-1 text-xs rounded-full font-medium transition-colors border sm:px-4 sm:py-1.5 sm:text-sm ${
                  selectedCategory === cat.category
                    ? "bg-gray-900 text-white border-gray-900"
                    : "bg-white text-gray-700 border-gray-300 hover:bg-gray-200"
                }`}
              >
                {cat.category === "all" ? "All" : cat.category}
              </button>
            ))}
          </div>
        </div>

        {/* FAQ Items */}
        <div className='border-t border-gray-200'>
          {filteredFaqs.length > 0 ? (
            filteredFaqs.map((category) => (
              <div key={category.category} className='mt-4 sm:mt-6'>
                <h2 className='text-lg sm:text-xl font-bold text-gray-800 mb-3 sm:mb-4 flex items-center gap-2'>
                  <category.icon className='w-5 h-5 text-blue-600' />
                  {category.category}
                </h2>
                <div className='border-t border-gray-200'>
                  {category.questions.map((item, index) => (
                    <FaqItem
                      key={index}
                      item={item}
                      isOpen={openItems[`${category.category}-${index}`]}
                      toggle={() => toggleItem(category.category, index)}
                    />
                  ))}
                </div>
              </div>
            ))
          ) : (
            <div className='text-center py-8 sm:py-10 bg-gray-200 rounded-lg border border-gray-200'>
              <p className='text-base text-gray-600'>
                No results found in{" "}
                {selectedCategory !== "all"
                  ? selectedCategory
                  : "all categories"}
                .
              </p>
              <p className='text-xs text-gray-500 mt-1'>
                Try selecting &quot;All&quot; questions.
              </p>
            </div>
          )}
        </div>

        {/* Contact CTA */}
        <div className='pt-6 sm:pt-8 text-center'>
          <p className='text-base text-gray-700 mb-3 sm:mb-4'>
            Still can&apos;t find the answer you&apos;re looking for?
          </p>
          <button className='inline-flex items-center justify-center px-5 py-2 text-sm sm:text-base border border-transparent font-medium rounded-lg text-white bg-blue-600 hover:bg-blue-700 transition-colors shadow-md'>
            Contact Support
          </button>
        </div>
      </div>
    </div>
  );
}
